### ISSUE TITLE
Object Keypoint Similarity

### ISSUE THREAD

**Issue by m5823779** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#1]
Nice work! Did you calculate sigmas (https://github.com/svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch/blob/03f53feaec447cf5f8e791dab9c8c9f853d49654/lib/nms/nms.py#L75) by yourself?

**Comment by ShenhanQian** [comment]
We just adopted sigmas provided by the DeepFashion2 dataset. Here is the source:
> https://github.com/switchablenorms/DeepFashion2/blob/cc5dd5721cede8d5f0041143e764c4bb0ef5f8e2/deepfashion2_api/PythonAPI/pycocotools/cocoeval.py#L206-L242

**Comment by m5823779** [comment]
Got it
Thanks~

**Comment by ShenhanQian** [comment]
You are welcome~
