### ISSUE TITLE
Bbox detector model missing

### ISSUE THREAD

**Issue by physxP** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#11]
I am aiming to create an inference pipeline for images in the wild. One of the problem that I am facing is to detect bboxs. Can you please upload the model and code for your detector? Otherwise there's also this repo that I found that can be used for this purpose:  https://github.com/archana1998/Clothing-Detection

**Comment by ShenhanQian** [comment]
You can try this [repo](https://github.com/ShenhanQian/KGDet) to detect clothes. Note that model checkpoints are provided there.

**Comment by physxP** [comment]
Many thanks! It would be great if this were also mentioned in the README.
