### ISSUE TITLE
    for catId in catIds}   File "/home/sa/anaconda3/envs/torch1.7/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 229, in computeOks     e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2 ValueError: operands could not be broadcast together with shapes (294,) (17,)

### ISSUE THREAD

**Issue by APeiZou** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#13]
训练的时候出现以下错误  
  for catId in catIds}
  File "/home/sa/anaconda3/envs/torch1.7/lib/python3.6/site-packages/pycocotools/cocoeval.py", line 229, in computeOks
    e = (dx**2 + dy**2) / vars / (gt['area']+np.spacing(1)) / 2
ValueError: operands could not be broadcast together with shapes (294,) (17,)
@ShenhanQian

**Comment by ShenhanQian** [comment]
本Repo面向DeepFashion2数据集，其包含294个关键点，因此需要安装DeepFashion2专用的`pycocotools`，即`deepfashion2_api`。而你使用的是原生的COCO数据集的`pycocotools`，其包含17个人体关键点，因此出现这行报错信息：
`ValueError: operands could not be broadcast together with shapes **(294,) (17,)**`。

请按照本repo提供的安装方法，正确安装`deepfashion2_api`。
