### ISSUE TITLE
Onedrive link has been deleted!

### ISSUE THREAD

**Issue by nvlong21** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#2]

**Comment by ShenhanQian** [comment]
Hi, I'm regretted to say that the original files have lost due to some bug of Onedrive. I'm working on re-arrangement of checkpoints

**Comment by yangnaGitHub** [comment]
have a nice work, and could you please provide your weights again, thanks

**Comment by ShenhanQian** [comment]
Hi, the OneDrive link is updated. You can check if it is accessible.

**Comment by yangnaGitHub** [comment]
> Hi, the OneDrive link is updated. You can check if it is accessible.

This link has already avilable, thanks a lot

**Comment by ShenhanQian** [comment]
You are welcome!
