### ISSUE TITLE
Question about the test result

### ISSUE THREAD

**Issue by xs020420** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#3]
Thanks for great job! And there is a question about the output of pretained model provided.
When I test pretained model, it return a tensor whose shape is [batchsize, 294, height, weight]. Could you give some expanation about the number "294" ?

**Comment by ShenhanQian** [comment]
Hi, 294 is the total number of keypoints defined in the DeepFashion2 dataset.
