### ISSUE TITLE
is top2down or botton2top? i find the model input is raw image not crop image

### ISSUE THREAD

**Issue by hyaihjq** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#4]

**Comment by ShenhanQian** [comment]
This is a top-down model. You can choose to feed in the ground-truth bounding boxes or predicted bounding boxes by setting the `USE_GT_BBOX` option. Then the program will crop the input image into patches for each instance before feeding them into the HRNet.

**Comment by hyaihjq** [comment]
thanks
