### ISSUE TITLE
File 'bbox_result_val.pkl' is not in the OneDrive link

### ISSUE THREAD

**Issue by WYK96** [svip-lab/HRNet-for-Fashion-Landmark-Estimation.PyTorch#6]
Thanks for sharing great job! However, when configuring the dataset, I cannot find bounding box results named 'bbox_result_val.pkl' in the provided OneDrive link. Did I miss anything?

**Comment by ShenhanQian** [comment]
Hi, I've updated the cloud storage. Please check if it is available from the same link.

**Comment by WYK96** [comment]
Yes, I could find it in the same link now. Thanks again.

**Comment by ShenhanQian** [comment]
You are welcome.
